# Generated by Django 3.1.6 on 2021-02-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
